'use strict';
// Minimal ESLint setup (user decision 2026-09-28, option B): only rules that find real mistakes, all as
// errors, no formatting or style rules, and no reformatting of existing code. The packages are dev
// dependencies of webagent-core/agent-host (CI runs `npm ci` there; the runtime install uses
// `npm ci --omit=dev`, so users never get them), hence they are resolved from that package.
// Run: cd webagent-core/agent-host && npm run lint
const { createRequire } = require('module');
const path = require('path');
const load = createRequire(path.join(__dirname, 'webagent-core/agent-host/package.json'));
const js = load('@eslint/js');
const globals = load('globals');

// eslint:recommended minus the rules that judge style or taste rather than correctness.
const notCorrectness = {
  'no-empty': 'off',               // empty catch blocks are a deliberate "ignore" pattern here
  'no-useless-escape': 'off',      // redundant escapes are harmless
  'no-control-regex': 'off',       // ANSI/control-character regexes are intentional (terminal output, sanitising)
  'no-prototype-builtins': 'off',  // style preference
  'no-extra-boolean-cast': 'off',  // style preference
  'no-useless-catch': 'off',       // style preference
  'no-regex-spaces': 'off',        // style preference
  'no-irregular-whitespace': 'off', // full-width spaces occur in Chinese comments and text
  // New in ESLint 10's recommended set. Dead initial values (`let ok = false; try { ok = … } catch { ok = false; }`)
  // are a deliberate defensive pattern here; all 19 hits at adoption were of that kind, none a real bug.
  'no-useless-assignment': 'off',
  // Asks for `{ cause }` when rethrowing: a diagnostics preference, and several places wrap errors on purpose so
  // internal details (paths, upstream bodies) are not passed on.
  'preserve-caught-error': 'off'
};

module.exports = [
  {
    // Not ours to change, generated, copied, or third-party.
    ignores: [
      '**/node_modules/**',
      'webagent-repro/**',                    // reproduction material, JS must not be modified
      'docs-site/content.js',                 // generated by docs-site/build.js
      'arena-model-probe/**', 'arena-trace-inspector/**', 'webagent-core/probe-extension/**', // the three probes (another assistant)
      'webagent-core/extensions-installed/**', // byte copy of webagent-core/extension (extensionCopy.test.js)
      'bin/**', '.cache/**', '.local/**', '.config/**', 'output/**', 'data/**', '**/.webagent/**'
    ]
  },
  {
    files: ['**/*.js', '**/*.cjs'],
    languageOptions: { ecmaVersion: 2024, sourceType: 'commonjs', globals: { ...globals.node } },
    linterOptions: { reportUnusedDisableDirectives: 'error' },
    rules: {
      ...js.configs.recommended.rules,
      ...notCorrectness,
      'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none', ignoreRestSiblings: true, varsIgnorePattern: '^_' }]
    }
  },
  {
    files: ['**/*.mjs'],
    languageOptions: { sourceType: 'module' }
  },
  {
    // Workbench front end: ES modules in the browser (and the VS Code settings webview).
    files: ['webagent-core/workbench/**/*.js'],
    languageOptions: { sourceType: 'module', globals: { ...globals.browser } }
  },
  {
    // Docs site shell: a classic browser script next to the generated content.js.
    files: ['docs-site/app.js'],
    languageOptions: { sourceType: 'script', globals: { ...globals.browser } }
  },
  {
    // The settings tab runs inside a VS Code webview, which provides acquireVsCodeApi.
    files: ['webagent-core/workbench/settings-panel.js'],
    languageOptions: { globals: { acquireVsCodeApi: 'readonly' } }
  },
  {
    // Playwright test: the callbacks passed to page.evaluate / waitForFunction run in the browser page.
    files: ['webagent-core/agent-host/tests/workbench.browser.js'],
    languageOptions: { globals: { ...globals.browser } }
  },
  {
    // This test installs window/document on Node's global object before using the bare names.
    files: ['webagent-core/agent-host/tests/probeTransport.test.js'],
    languageOptions: { globals: { window: 'writable', document: 'writable' } }
  }
];
