'use strict';
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { config } = require('../src/config');
const store = require('../src/models/store');
const { runChat, planRound } = require('../src/agent/runChat');
const { runOpenAI } = require('../src/agent/openai');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'webagent-model-life-'));
const priorWorkspace = config.workspaceRoot, priorFetch = global.fetch;
config.workspaceRoot = tmp;
const model = { id: 'test', protocol: 'openai', apiKey: 'fixture', baseUrl: 'https://model.invalid/v1', modelId: 'fixture' };
const reply = message => ({ ok: true, text: async () => JSON.stringify({ choices: [{ message }] }) });
(async () => {
  store.save({ ...store.defaults(), activeModelId: 'test', models: [model] });
  const events = [];
  global.fetch = async () => { throw new Error('fixture model unavailable'); };
  await runChat({ mode: 'code', message: '创建 note.txt\n```text\nhello\n```' }, (type, data) => events.push({ type, ...data }));
  assert.ok(events.some(e => e.type === 'error' && /已停止/.test(e.message)));
  assert.ok(!events.some(e => e.type === 'tool'));
  assert.ok(!fs.existsSync(path.join(tmp, 'note.txt')));
  let requests = 0;
  global.fetch = async (_, options) => {
    requests++;
    if (requests === 1) return reply({ role: 'assistant', content: null, tool_calls: Array.from({ length: 9 }, (_, i) => ({ id: 'call-' + i, type: 'function', function: { name: 'list_directory', arguments: '{"dirPath":"."}' } })) });
    const messages = JSON.parse(options.body).messages;
    const tools = messages.filter(m => m.role === 'tool');
    assert.strictEqual(tools.length, 9);
    assert.strictEqual(JSON.parse(tools[8].content).ok, false);
    return reply({ role: 'assistant', content: 'done' });
  };
  assert.strictEqual((await runOpenAI({ mode: 'ask', message: 'list', history: [], model })).text, 'done');
  let finish;
  global.fetch = () => new Promise(resolve => { finish = resolve; });
  const oldTask = runChat({ mode: 'plan', message: 'first plan' }, () => {});
  assert.ok(finish);
  planRound.start({ task: 'second plan', maxBranches: 4 });
  finish(reply({ role: 'assistant', content: 'old plan answer' }));
  await oldTask;
  assert.strictEqual(planRound.current().task, 'second plan');
  assert.strictEqual(planRound.current().branches.length, 0);
  planRound.addBranch({ answer: 'one' }); planRound.addBranch({ answer: 'two' });
  const merging = runChat({ mode: 'plan', planAction: 'merge' }, () => {});
  planRound.addBranch({ answer: 'third arrived during merge' });
  finish(reply({ role: 'assistant', content: 'outdated merge' }));
  await merging;
  assert.strictEqual(planRound.current().merged, null);
  console.log('model failure/tool-result/Plan generation regressions passed');
})().catch(err => { console.error(err); process.exitCode = 1; }).finally(() => {
  config.workspaceRoot = priorWorkspace; global.fetch = priorFetch; planRound.reset();
  fs.rmSync(tmp, { recursive: true, force: true });
});
